export const MAGUI_CONNECT_PRESETS = [
  {
    id: "graphite",
    name: "Graphite",
    themeAccent: "#ffffff",
    themeBackground: "#111111",
    themeForeground: "#f5f5f5",
    buttonStyle: "sharp",
    cardStyle: "glass",
    fontStyle: "sans",
  },
  {
    id: "ivory",
    name: "Ivory",
    themeAccent: "#111111",
    themeBackground: "#ffffff",
    themeForeground: "#111111",
    buttonStyle: "rounded",
    cardStyle: "solid",
    fontStyle: "serif",
  },
  {
    id: "ink",
    name: "Ink",
    themeAccent: "#3b82f6",
    themeBackground: "#020617",
    themeForeground: "#f8fafc",
    buttonStyle: "default",
    cardStyle: "glass",
    fontStyle: "sans",
  },
  {
    id: "frost",
    name: "Frost",
    themeAccent: "#0ea5e9",
    themeBackground: "#f8fafc",
    themeForeground: "#0c4a6e",
    buttonStyle: "rounded",
    cardStyle: "glass",
    fontStyle: "sans",
  },
  {
    id: "editorial",
    name: "Editorial",
    themeAccent: "#991b1b",
    themeBackground: "#fffafb",
    themeForeground: "#450a0a",
    buttonStyle: "sharp",
    cardStyle: "flat",
    fontStyle: "serif",
  },
]
