export const MAGUI_CONNECT_PRESETS = [
  {
    id: "magui-signature",
    name: "MAGUI Signature",
    themeAccent: "#E5FF00", // Lima MAGUI
    themeBackground: "#050505",
    themeForeground: "#FFFFFF",
    buttonStyle: "rounded-full",
    cardStyle: "glass-glow",
    fontStyle: "system-sans",
  },
  {
    id: "stealth-luxury",
    name: "Stealth Luxury",
    themeAccent: "#C0C0C0",
    themeBackground: "#0A0A0B",
    themeForeground: "#E0E0E0",
    buttonStyle: "sharp",
    cardStyle: "glass-border",
    fontStyle: "wide-sans",
  },
  {
    id: "architect-white",
    name: "Pure Architect",
    themeAccent: "#000000",
    themeBackground: "#FFFFFF",
    themeForeground: "#1A1A1A",
    buttonStyle: "default",
    cardStyle: "minimal-shadow",
    fontStyle: "serif",
  },
  {
    id: "neon-cyan",
    name: "Digital Cyan",
    themeAccent: "#00FFF2",
    themeBackground: "#01080A",
    themeForeground: "#F0FDFF",
    buttonStyle: "pill",
    cardStyle: "neon-border",
    fontStyle: "mono",
  },
  {
    id: "executive-gold",
    name: "Executive Gold",
    themeAccent: "#D4AF37",
    themeBackground: "#1A1A1A",
    themeForeground: "#F5F5F5",
    buttonStyle: "soft-rounded",
    cardStyle: "flat",
    fontStyle: "classic-serif",
  },
  {
    id: "deep-ocean",
    name: "Deep Ocean",
    themeAccent: "#38BDF8",
    themeBackground: "#030712",
    themeForeground: "#F8FAFC",
    buttonStyle: "default",
    cardStyle: "glass",
    fontStyle: "sans",
  },
  {
    id: "nordic-minimal",
    name: "Nordic Minimal",
    themeAccent: "#5E81AC",
    themeBackground: "#ECEFF4",
    themeForeground: "#2E3440",
    buttonStyle: "rounded-2xl",
    cardStyle: "flat-border",
    fontStyle: "sans",
  },
]

export const MAGUI_CONNECT_LINK_KIND_PRESETS = [
  { value: "LINK", label: "Link Padrão", icon: "Link" },
  { value: "WHATSAPP", label: "WhatsApp", icon: "WhatsappLogo" },
  { value: "INSTAGRAM", label: "Instagram", icon: "InstagramLogo" },
  { value: "LINKEDIN", label: "LinkedIn", icon: "LinkedinLogo" },
  { value: "EMAIL", label: "E-mail", icon: "Envelope" },
  { value: "PHONE", label: "Telefone", icon: "Phone" },
  { value: "PORTFOLIO", label: "Portfólio", icon: "Briefcase" },
  { value: "SHOP", label: "Loja Virtual", icon: "ShoppingBag" },
  { value: "YOUTUBE", label: "YouTube", icon: "YoutubeLogo" },
  { value: "BEHANCE", label: "Behance", icon: "BehanceLogo" },
  { value: "DRIBBBLE", label: "Dribbble", icon: "DribbbleLogo" },
  { value: "GITHUB", label: "GitHub", icon: "GithubLogo" },
]
